/**
 * pdfExport.js - Reusable PDF generation helpers using jsPDF.
 */

import jsPDF from 'jspdf';

const C = {
  bg:        [9,   9,  11],
  card:      [17,  17, 19],
  border:    [39,  39, 42],
  primary:   [244, 244, 245],
  secondary: [161, 161, 170],
  muted:     [113, 113, 122],
  indigo:    [129, 140, 248],
  emerald:   [52,  211, 153],
  amber:     [251, 191, 36],
  rose:      [248, 113, 113],
  cyan:      [56,  189, 248],
};

function setFill(pdf, rgb) { pdf.setFillColor(...rgb); }
function setDraw(pdf, rgb) { pdf.setDrawColor(...rgb); }
function setTxt(pdf, rgb)  { pdf.setTextColor(...rgb); }

function fillRect(pdf, x, y, w, h, rgb) {
  setFill(pdf, rgb); pdf.rect(x, y, w, h, 'F');
}

function hline(pdf, x1, y, x2, rgb, lw = 0.2) {
  setDraw(pdf, rgb); pdf.setLineWidth(lw); pdf.line(x1, y, x2, y);
}

function txt(pdf, str, x, y, opts = {}) {
  pdf.setFontSize(opts.size || 10);
  setTxt(pdf, opts.color || C.primary);
  pdf.setFont('helvetica', opts.bold ? 'bold' : 'normal');
  pdf.text(String(str == null ? '' : str), x, y, { align: opts.align || 'left' });
}

function pageHeader(pdf, title, pageW) {
  fillRect(pdf, 0, 0, pageW, 18, C.bg);
  setFill(pdf, C.indigo); pdf.rect(0, 0, 3, 18, 'F');
  txt(pdf, 'AuraCareer', 7, 7,  { size: 6.5, color: C.indigo, bold: true });
  txt(pdf, title,        7, 13, { size: 8.5, color: C.primary, bold: true });
  txt(pdf, new Date().toLocaleString(), pageW - 6, 7, { size: 5.5, color: C.muted, align: 'right' });
}

function pageFooter(pdf, n, total, pageW, pageH) {
  hline(pdf, 0, pageH - 10, pageW, C.border);
  txt(pdf, `Page ${n} of ${total}`, pageW / 2, pageH - 4.5, { size: 6.5, color: C.muted, align: 'center' });
  txt(pdf, 'Generated by AuraCareer', 8, pageH - 4.5, { size: 6, color: C.muted });
}

// ── 1. Analysis Report PDF ─────────────────────────────────────────────────
export async function downloadAnalysisPDF(resumeData) {
  if (!resumeData) return;

  const pdf = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const PW  = pdf.internal.pageSize.getWidth();
  const PH  = pdf.internal.pageSize.getHeight();
  const M   = 13;
  const col = PW - M * 2;
  let y     = 24;

  const addPage = () => {
    pdf.addPage();
    fillRect(pdf, 0, 0, PW, PH, C.bg);
    pageHeader(pdf, 'Resume Analysis Report (continued)', PW);
    y = 24;
  };
  const checkY = (need = 20) => { if (y + need > PH - 14) addPage(); };

  fillRect(pdf, 0, 0, PW, PH, C.bg);
  pageHeader(pdf, 'Resume Analysis Report', PW);

  const ats   = resumeData.ats_results || {};
  const score = ats.overall_score || 0;
  const tier  = ats.tier || '';
  const name  = resumeData.candidate_name || resumeData.contact_info?.name || 'Candidate';
  const role  = resumeData.target_role || 'General';
  const ci    = resumeData.contact_info || {};

  txt(pdf, name, M, y, { size: 14, bold: true });
  y += 6;
  txt(pdf, role, M, y, { size: 8.5, color: C.indigo });
  y += 5;
  const contacts = [ci.email, ci.phone, ci.linkedin].filter(Boolean).join('   |   ');
  if (contacts) { txt(pdf, contacts, M, y, { size: 7.5, color: C.secondary }); y += 5; }
  hline(pdf, M, y, PW - M, C.border); y += 6;

  // ATS Score
  const sc = score >= 80 ? C.emerald : score >= 60 ? C.amber : C.rose;
  fillRect(pdf, M, y, 50, 16, C.card);
  setDraw(pdf, sc); pdf.setLineWidth(0.5); pdf.roundedRect(M, y, 50, 16, 2, 2, 'S');
  txt(pdf, String(score), M + 14, y + 10, { size: 15, color: sc, bold: true, align: 'center' });
  txt(pdf, 'ATS SCORE', M + 33, y + 7,  { size: 6, color: C.muted, bold: true });
  txt(pdf, tier,         M + 33, y + 12, { size: 7, color: sc });

  const meta   = resumeData.metadata || {};
  const skills = resumeData.skills || {};
  const stats  = [
    ['Skills', (skills.technical?.length || 0) + (skills.soft?.length || 0)],
    ['Words',  meta.word_count || '—'],
    ['Pages',  meta.page_count || '—'],
  ];
  let sx = M + 58;
  stats.forEach(([lbl, val]) => {
    txt(pdf, String(val), sx, y + 8,  { size: 13, color: C.primary, bold: true });
    txt(pdf, lbl,         sx, y + 13, { size: 6.5, color: C.muted });
    sx += 38;
  });
  y += 22;

  // Score Breakdown
  hline(pdf, M, y, PW - M, C.border); y += 6;
  txt(pdf, 'SCORE BREAKDOWN', M, y, { size: 7.5, color: C.muted, bold: true }); y += 5;

  const bd = ats.breakdown || {};
  const bars = [
    { label: 'Keyword Match',         v: bd.keyword_match?.score, max: bd.keyword_match?.max_score  || 25 },
    { label: 'Action Verbs',          v: bd.action_verbs?.score,  max: bd.action_verbs?.max_score   || 20 },
    { label: 'Quantifiable Metrics',  v: bd.metrics?.score,       max: bd.metrics?.max_score        || 20 },
    { label: 'Formatting',            v: bd.formatting?.score,    max: bd.formatting?.max_score     || 15 },
    { label: 'Readability',           v: bd.readability?.score,   max: bd.readability?.max_score    || 10 },
    { label: 'Section Coverage',      v: bd.sections?.score,      max: bd.sections?.max_score       || 10 },
  ];
  const barTrack = col * 0.5;
  bars.forEach(b => {
    checkY(8);
    const pct  = b.max ? Math.min((b.v || 0) / b.max, 1) : 0;
    const fill = pct >= 0.8 ? C.emerald : pct >= 0.6 ? C.amber : C.rose;
    txt(pdf, b.label, M, y + 3.5, { size: 7.5, color: C.secondary });
    fillRect(pdf, M + 50, y, barTrack, 5, [25, 25, 30]);
    if (pct > 0) fillRect(pdf, M + 50, y, barTrack * pct, 5, fill);
    txt(pdf, `${b.v ?? 0}/${b.max}`, M + 50 + barTrack + 3, y + 3.5, { size: 7, color: C.secondary });
    y += 8;
  });

  // Skills
  const allSkills = [...(skills.technical || []), ...(skills.soft || [])].slice(0, 40);
  if (allSkills.length) {
    checkY(16);
    hline(pdf, M, y, PW - M, C.border); y += 6;
    txt(pdf, 'DETECTED SKILLS', M, y, { size: 7.5, color: C.muted, bold: true }); y += 5;
    let px = M;
    allSkills.forEach(sk => {
      const lbl = String(sk);
      const w   = Math.max(lbl.length * 1.65 + 5, 12);
      if (px + w > PW - M) { px = M; y += 7; checkY(7); }
      fillRect(pdf, px, y - 4, w, 6, [28, 28, 34]);
      txt(pdf, lbl, px + w / 2, y, { size: 6, color: C.indigo, align: 'center' });
      px += w + 2;
    });
    y += 10;
  }

  // AI Critique
  const critique = resumeData.ai_critique || {};
  if (critique.summary) {
    checkY(20);
    hline(pdf, M, y, PW - M, C.border); y += 6;
    txt(pdf, 'EXECUTIVE CRITIQUE', M, y, { size: 7.5, color: C.muted, bold: true }); y += 5;
    const lines = pdf.splitTextToSize(critique.summary, col);
    lines.forEach(l => { checkY(5); txt(pdf, l, M, y, { size: 8, color: C.secondary }); y += 4.5; });
    y += 3;
  }

  // Strengths & Improvements
  const strengths    = critique.strengths    || [];
  const improvements = critique.improvements || critique.weaknesses || [];
  if (strengths.length || improvements.length) {
    checkY(30);
    hline(pdf, M, y, PW - M, C.border); y += 6;
    const half = col / 2 - 4;
    txt(pdf, 'STRENGTHS',    M,          y, { size: 7.5, color: C.emerald, bold: true });
    txt(pdf, 'IMPROVEMENTS', M + half + 8, y, { size: 7.5, color: C.amber,   bold: true });
    y += 5;
    const maxRows = Math.min(Math.max(strengths.length, improvements.length), 8);
    for (let i = 0; i < maxRows; i++) {
      checkY(5);
      if (strengths[i]) {
        const l = pdf.splitTextToSize('• ' + strengths[i], half);
        txt(pdf, l[0], M, y, { size: 7.5, color: C.secondary });
      }
      if (improvements[i]) {
        const l = pdf.splitTextToSize('• ' + improvements[i], half);
        txt(pdf, l[0], M + half + 8, y, { size: 7.5, color: C.secondary });
      }
      y += 5.5;
    }
  }

  // Finalize
  const total = pdf.internal.getNumberOfPages();
  for (let i = 1; i <= total; i++) { pdf.setPage(i); pageFooter(pdf, i, total, PW, PH); }

  const safeName = (resumeData.candidate_name || 'resume').replace(/\s+/g, '_');
  pdf.save(`${safeName}_analysis_${new Date().toISOString().slice(0, 10)}.pdf`);
}

// ── 2. Admin Table PDF ─────────────────────────────────────────────────────
export function downloadTablePDF(rows, columns, headers, title, filename) {
  const pdf  = new jsPDF({ orientation: 'landscape', unit: 'mm', format: 'a4' });
  const PW   = pdf.internal.pageSize.getWidth();
  const PH   = pdf.internal.pageSize.getHeight();
  const M    = 10;
  const col  = PW - M * 2;
  const cw   = col / columns.length;
  let y      = 24;
  let page   = 1;

  const drawTHead = () => {
    fillRect(pdf, M, y, col, 7.5, [28, 28, 36]);
    let cx = M;
    headers.forEach(h => {
      txt(pdf, h.toUpperCase(), cx + 2, y + 5, { size: 6, color: C.indigo, bold: true });
      cx += cw;
    });
    y += 9;
    hline(pdf, M, y, M + col, C.border, 0.3);
  };

  const newPage = () => {
    const tot = pdf.internal.getNumberOfPages();
    pageFooter(pdf, page, tot, PW, PH);
    pdf.addPage();
    fillRect(pdf, 0, 0, PW, PH, C.bg);
    pageHeader(pdf, title + ' (continued)', PW);
    y = 24; page++;
    drawTHead();
  };

  fillRect(pdf, 0, 0, PW, PH, C.bg);
  pageHeader(pdf, title, PW);
  txt(pdf, `${rows.length} records  \u2022  ${new Date().toLocaleDateString()}`, M, y, { size: 7.5, color: C.secondary });
  y += 6;
  drawTHead();

  rows.forEach((row, ri) => {
    if (y > PH - 16) newPage();
    if (ri % 2 === 0) fillRect(pdf, M, y - 1, col, 7.5, [15, 15, 19]);
    let cx = M;
    columns.forEach(key => {
      const raw     = row[key] == null ? '' : row[key];
      const disp    = typeof raw === 'object' ? JSON.stringify(raw) : String(raw);
      const clipped = pdf.splitTextToSize(disp, cw - 3)[0];
      txt(pdf, clipped, cx + 2, y + 4.5, { size: 6.5, color: C.secondary });
      cx += cw;
    });
    y += 7.5;
    hline(pdf, M, y - 0.5, M + col, C.border, 0.1);
  });

  const total = pdf.internal.getNumberOfPages();
  for (let i = 1; i <= total; i++) { pdf.setPage(i); pageFooter(pdf, i, total, PW, PH); }
  pdf.save(`${filename}_${new Date().toISOString().slice(0, 10)}.pdf`);
}
